CREATE TABLE [dbo].[ScreenShot]
(
	id UNIQUEIDENTIFIER ROWGUIDCOL PRIMARY KEY NOT NULL,
	userName VARCHAR(256) NOT NULL,
	timeStamp DATETIME NOT NULL,
	image VARBINARY(MAX) FILESTREAM NOT NULL
)
